### ISSUE TITLE
Digital out level raises exception

### ISSUE THREAD

**Issue by fengalin** [fengalin/gstation-edit#29]
When changing digital out level, the following exception occurs:
Traceback (most recent call last):
  File "/home/francois/Projects/gstation-edit/gstation_edit/ui_core/scale_parameter.py", line 66, in handle_change_value
    self.set_value(int_value)
  File "/home/francois/Projects/gstation-edit/gstation_edit/ui_core/scale_parameter.py", line 58, in set_value
    self.value_lbl.set_text(self.str_value)
AttributeError: 'NoneType' object has no attribute 'set_text'

**Comment by fengalin** [comment]
The scale needs to be migrated to the new model with a separate label (introduced in #3).
